1.9.8

diff --git a/tools/android-sdk/mainDexClasses b/tools/android-sdk/mainDexClasses
--- a/tools/android-sdk/mainDexClasses
+++ b/tools/android-sdk/mainDexClasses
@@ -58,8 +58,14 @@ prog="${progdir}"/`basename "${prog}"`
 cd "${oldwd}"
 
 baserules="${progdir}"/mainDexClasses.rules
-if [ ! -r ${baserules} ]; then
+if [ ! -r "${baserules}" ]; then
     echo `basename "$prog"`": can't find mainDexClasses.rules" 1>&2
+    exit 1
+fi
+
+extrarules="${progdir}"/mainDexClassesNoAapt.rules
+if [ ! -r ${extrarules} ]; then
+    echo `basename "$prog"`": can't find mainDexClassesNoAapt.rules" 1>&2
     exit 1
 fi
 
@@ -150,6 +156,9 @@ if expr "x$1" : 'x--output' >/dev/null; then
 elif expr "x$1" : 'x--disable-annotation-resolution-workaround' >/dev/null; then
     disableKeepAnnotated=$1
     shift 1
+elif expr "x$1" : "x--aapt-rules" >/dev/null; then
+    extrarules=$2
+    shift 2
 else
     break
 fi
@@ -164,8 +173,8 @@ tmpOut=`makeTempJar`
 
 trap cleanTmp 0
 
-${proguard} -injars ${@} -dontwarn -forceprocessing  -outjars ${tmpOut} \
+"${proguard}" -injars ${@} -dontwarn -forceprocessing  -outjars "${tmpOut}" \
   -libraryjars "${shrinkedAndroidJar}" -dontoptimize -dontobfuscate -dontpreverify \
-  -include "${baserules}" 1>/dev/null || exit 10
+  -include "${baserules}" -include "${extrarules}" 1>/dev/null || exit 10
 
 java -cp "$jarpath" com.android.multidex.MainDexListBuilder ${disableKeepAnnotated} "${tmpOut}" ${@} ||  exit 11
